project:
  type: website

website:
  site-url: https://economic-analytics.co.uk/
  page-footer: 
    center: © Copyright 2026, [Economic Analytics](https://economic-analytics.co.uk)
    right: Built by [Economic Analytics](https://economic-analytics.co.uk) and powered by [Quarto](https://quarto.org)
    background: "#00CCFF"
  title: "Economic Analytics"
  navbar:
    pinned: true
    background: "#0000FF"
    logo: img/ea-logo.png
    left:
      - about.qmd
      - services.qmd
      - blog.qmd
      - explainers.qmd
      - contact.qmd
    right:
      - icon: bluesky
        href: https://bsky.app/profile/economic-analytics.co.uk
        target: _blank
      - icon: twitter-x
        href: https://x.com/EconAnalyticsUK
        target: _blank
      - icon: linkedin
        href: https://linkedin.com/company/economic-analytics
        target: _blank
      - icon: github
        menu:
          - text: Economic Analytics
            href: https://github.com/economic-analytics
            target: _blank
          - text: Website source code
            href: https://github.com/economic-analytics/economic-analytics.co.uk
            target: _blank
format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    theme: default
    css: styles.css