---
title: "Introducing Explainers"
author: "Christian Spence"
date: "2026-06-19"
categories: [explainers]
---

Over the past decade and a half, I've given more presentations, attended roundtables, and taught classes on the various byways of economics, economic policy and financial and commodity markets than I could ever remember. With the old adage that if you want to truly learn about a subject, teach it, the learning curve, even for one's own specialist subject, never stops.

But with all of that delivering information to clients comes, for me, one of the most challenging yet enjoyable parts of the job: answering the audience's questions at the end of the presentation. In my experience, these tend to fall into three main categories.

Many will be simple points of clarification. For me, these form perhaps the strongest feedback loop on my own presentation style. I tend to take these as a signal that I wasn't sufficiently clear in what I was saying, and aim to do better next time. As the subject professional, it's my job to make things clear to the audience and, if I haven't done that, I've failed. I try to stick to the maxim of "treat your audience as intelligent, but don't assume subject knowledge". In most cases that works, but one people ask for clarification, that's a good learning opportunity.

In other cases, while the question is a hard one from the attendee's point of view, for the subject expert they're often (and perhaps should be) easily answerable. This is where most questions tend to fall: the person asking doesn't have deep knowledge of the area they're asking you about, and are keen to understand your opinion on the topic.

Sometimes you get the question which catches you out: either it's further from the topic you've just presented on and so the answer needs compiling from a part of your brain which hasn't been active on that day, or they're genuinely tricky. Questions around policy and politics tend to fall into this category most often, but an audience member is always capable of catching you out. For these, I try to answer to the best of my ability and, if it's truly a challening one, then setting out the arguments around the question on both sides, setting additional context and adding some historic examples or theory can help to clarify for the questioner even if you don't have a perfect answer. And critically, if you don't know, say so! I was thankfully taught from an early age that it's perfectly reasonable to not know something, but you should know how to find out. Be honest, say you don't know and ask the questioner to catch you afterwards and offer to follow-up with them when you've had a chance to do some research and thinking. My experience is that people genuinely respect both your honesty and your willingness to chase down an answer.

There are some questions, however, that fall into all of the above categories: questions I tend to call "explainers". They're variously asked by people seeking clarifications, seeking deeper knowledge, or setting an issue in their minds into a broader context. Over the years, there's a number of these that just keep coming up, time after time. Whether the audience is the general public, business owners, public sector, lawyers, financiers or anyone else, there are some things about the economic world that many, many people just either don't understand at all, or have serious questions about precisely how it works, even if they have a general idea.

Common areas on this are bond markets (why do yields go up when prices come down), energy pricing markets (why is "free" renewable energy so expensive), labour markets (how can both employment and unemployment rise/fall at the same time), taxation (why am I double taxed on so many things, how dare you call my dividends unearned income), local government (how do they spend so much money when they can't empty my bins), and many more. Having to repeatedly answer these questions to a variety of people with very different backgrounds and understanding of different parts of the world gives you lots of experience in answering these in different ways and gives you a glimpse into which parts of my own professional world are well understood and where people tend to have knowledge gaps.

So, [this new part of the website, "Explainers"](/explainers/) is dedicated to answering these sorts of questions. The ones that come up over and over again from all sorts of different people. I hope it will prove a useful resource, as well as improving my own knowledge in how to best put these issues across clearly in the future.