---
title: "Andy Burnham to Westminster"
subtitle: "The King of the North goes South"
author: "Christian Spence"
date: "2026-06-22"
categories: [labour, pm, burnham]
---
Today saw Andy Burnham, ex-Mayor of Greater Manchester, journeying south (with the ridiculous spectacle of the Sky News helicopter following his train) to be sworn in as MP for Makerfield after a resounding win last week. Today also, for the sixth time in the past decade, a prime minister at the lectern in Downing Street saying he can't carry on and resigning the position.

In some ways, the decadal span of these six resignations tells you much about the state of UK politics. Tomorrow will be the 10th anniversary of the referendum of the United Kingdom voting to leave the European Union. (The fact that at 50 this year, I saw the same number of prime ministers in my first 40 years as I have in the last 10 perhaps says even more.) Clearly, the visuals of Starmer resigning in Downing Street (technically only as Labour party leader: he'll remain PM until his successor takes over) and Andy Burnham arriving sums up the likely next steps. Wes Streeting (former health secretary) has said he won't stand for the leadership and will back Burnham, so a coronation rather than a leadership contest now seems to be the outcome (meaning Burnham may be in number 10 by mid-July).

Plenty has been written on who the "real" Burnham is ([this piece by Jennifer Williams at the Financial Times (£)](https://www.ft.com/content/9dd44b54-2271-4687-a146-064f35fe9936?syn-25a6b1a6=1) is excellent), contrasting both his time in Westminster in government and opposition (including under Corbyn) and his recent years as mayor of Greater Manchester. That he is charismatic and personable is clear, and that alone makes a positive contrast to the dull managerialism of Starmer's reign, but ultimately being a regional mayor is not the same job as prime minister. The trade offs will be brutal and, in this febrile political climate, he'll have only a very short window to make it clear how the remaining three years of this parliament will be more successful than the first two.

Where his platform is currently light, perhaps understandably at this stage, is on policy. What will he do differently? The core constraints will remain the same, even though there is room to do things differently with the right policies and - crucially - the right narrative. And he has only three years to the next election, which means anything painful needs to start really very soon. A little light Manchester-style boosterism isn't going to cut it at the national level with Reform watching on for the first mistake.

I wish him well: I hope others do, too. But with a batting average of two years per prime minister over the past decade, he'll have to play a very different game to his predecessors if he - and we - are to be successful.