---
title: "Burnham's first conference speech as PM"
subtitle: "Scrapping the triple lock, social care reform and proportional representation"
author: "Christian Spence"
date: "2026-09-29"
categories: [labour conference, burnham, budget 2026]
draft: true
---
"All together now"

Draw a line on a decade of division

Stop doomscrolling

Put the country on a new path

britain with elief again, people with hope again

10 weeks into this job

politics as usual has taken it backwards
going to break the mould

frustration with westminster
refusal to treat all parts of the country equally and fairly hillsbrough
social care crisis

outsider to westminster club
makerfield by-election - not missed westminster, come back to change it
make politics work for "you"

life is too expensive
less drift, more direction

hope comes from honesty

honesty: saying things politicians usually avoid
say it straight - britain on wrong path for a long time

deindustriaisation, [others] brexit, austerity, power in too few hands, too many places left to drift

put britain on a new path

new economy, new politics

we built the common good until the 1980s
wealth for the many became opportunity for the few
homes, wealth, transport, energy, care
broken up and sold off

british right gave away control in the first place (to private sector/individuals?)

10 year plan coming

growth in every postcode, hope in every heart

reform of right to buy - remove from new homes

empty homes - back into public housing stock

poor quality private rented stock - issues of absent landlords, paid through benefit system
warnings - much easier for LAs to acquire homes, legislate if necessary

Your First Home - reduce deposit

new bill before Christmas - leasehold reform

housing > water - a symbol of what has gone wrong with Britain
shareholders never lose, public never wins
water bill to parliament - repeal of Thatcher ban on public ownership of water companies
start a ten-year journey to a different system, strengthen public control, mayors have new powers to hold watre companies to account

energy market reform
grid connectivity
national energy plan: local democratic control, mayors & local leaders, great british grid (branch of GBE)
publically owned operator
energy, water, housing, back under stronger public control

VAT off electricity bill this Thursday

From Jan 2027, paying no more than £2 for a single bus journey
These things are not everything - but a sign of intent to get bills and fares down as you wait for the bigger changes to come

Stick to fiscal rules

Council homes > save housing benefit
Energy bills down > get inflation down
Chnge way support people > get benefits bill down

Plan for public control is a plan for growth
People, places, businesses

Stucjk in hopsital as no home care

Beveridge report - need social contract fro 21 century

Reform of social care - long held ambition
Care workers - you are not invisible to me
I see you, I thank you, and I am sorry that my profession has let down yours for so long
Care Service that starts in the home
system where everyone contributes and everyone [benefits] - free at the point of use
no charges paid out of basic state pension
peace of mind
protects peoples homes and savings
proper recognition to care workers we'll all need to rely on
National Care Service we will build
fewer ambulance call outs, fewer a+e admissions, fewer [something - stuck in hospital?] - theme of invest to save
- but triple lock promise for this parliament will be honoured
- take to record high
from there - in April 2030 adjust it - SP will rise by prices or 2.5%, earnings over time - pensioners share in rising prosperity of nation
will generate signifcant savings which we will use to build up national care service

low-income pensioners won't pay IT in this parliament
will go out and argue for it

same boldness for young people too
growing up got harder in the sm age
youth services, practi abolished, children's MH services cut
families left ot battle for support for kids with SEN and disabilities
cast adrift, overly focused on university route
politicians fail to give support, yhen threaten to strip away in their 20s

invest or pay for failure
await final report of Milburn review 
change education and welfare system
rebuild system of comprehesive education in this country
with parity between academic and technical routes

45 day work exp, apprenticehsips no waiting, ...
need reform of welfare system to help pay for these
philoosphy of social security invest in success, rather than pay for failure?[...]

easier to meet NATO obligations on defence
match ambitions on the international domain

principled in our leadership - two state solution Israel Palestine

This is the labour way.
Enhance social security and our national security

Britain is not safer wth a younger generation without hope

Theory of grwoth - take control of essentialt sthat male a place work = fundamental things
From there - devolve more power to places - put tem in charge to decide tehir own destiny
Optimise conditions for businesses to grow, support our poepl so they're there for businesses to employ
Develoepd this approach leading fasting-growing city region

Take what I did in Macester and drive inot the very centre of government
Overtsee rewiring ofthe briiths state, re []..] reinudryialstion of regions

require culture change in whitehall

mayor of liverpool cr shoudl not have had to fight whitehall to het new ferry built on bnak of river mersey

AI

UK heads G20 next year

unlicks working class aspiration

one final thing we need to change - our politics

westm priiotoes point sorign over probme solving
need to change ourselves
will work get cross-arty support for our plan for britian
project confidecne and stability ot markets about uks future direction
cant succedd if we continue with levels of political turbulence
7th pm in 10 years
underpin plan for britian with a new politics
we will all have failed in our public durite sif we carry on as we are and open door of no 10 to a divisie PM on less than 30% of thevote
in past years, you have voted twice to support electoral reform
and todya ia m annoncing  a new antional commissio on electoral refrom
manifesto commitment ot changfe the electoral system

Brexit hasn't given us control
WE'v lsot control over economy
decade of low growht
lost control over immigration
debate about fairness - understand the anger
small boates down 40%
net mogrtion down 80% from johnson
alwasy be grateful for thsoe who have come here and are contributing to our country

control over immigration lost collaboration
UK-EU summit - work togerther on immigration
gains fro British industries for business harmed by Brexit
not give Britain clear path until we decide on a long-term relationship with what is still our largest market
I cannot say that where we are is good enough
brexit has done more harm than good
we need ot restore a hgiher-level of growth of prosperity
take opoprtunity to lay out different options for relationship with EU
find concesus around one
