---
title: "VAT removed on domestic electricity"
subtitle: "Good decision? Probably not, but ..."
author: "Christian Spence"
date: "2026-07-21"
categories: [policy, vat, cost of living]
---

On only the second day of his premiership, new Prime Minister Andy Burnham is already making policy announcements around the cost of living, one of his core areas of focus. The proposal is simple enough: the current reduced rate of VAT of 5% applied to domestic electricity consumption is to be scrapped (technically, reduced to 0%).

Almost all economists and tax policy specialists will say that this is (a) a trivial household saving (around £45 per year), (b) an expensive tax cut at the national level (around £800m per year), and (c) a further level of complexity in what is already one of the most complex VAT schemes in the developed world. Left-leaning thinktanks and poverty organisations have mostly reacted positively to the news (for the poorest households, small savings make a bigger difference), though issues have been raised that richer households (who consume more electricity than poorer ones) will see a larger cash saving, though smaller as a percentage of their overall income.

Prices are volatile (smoothed by the Ofgem price cap), and cuts of this size are easily wiped out by wider market movements

Ultimately, all of the above are true, but I think it's worth exploring in more detail some other ways of thinking about this as a policy response.

Savings per household are small, but at the bottom of the distribution, this is still valuable. It is, however, expensive to give the richest households a discount on their electricity bill.

£800m per year is not a huge amount (the government spends £1,300bn each year, so this is less than a tenth of one percent) but, in a climate where the government is still borrowing to fund current expenditure, these billions soon start to add up.

The complexity of the UK's VAT system is well known: we have the largest share of overall consumption in reduced, zero-rated and exempt categories, and some of these are hard to justify. Whilst I can see a case (though personally wouldn't choose it) for levying a reduced-rate of VAT on domestic energy consumption (the rate of 5% applies to both gas and electricity), reducing this to zero for electricity has a number of issues beyond simple policy complexity.

Firstly, whilst reducing the relative cost of domestic electricity (from 5% to 0%) compared to domestic gas (5%) it should incentivise switching between the two, it creates no incentive for industrial switching and _increases_ the discrepancy between domestic and commercial tax on energy. Electricity consumed at home: 5% (soon to be 0%); electricity consumed outside the home, 20%. This distortion in felt in a number of ways, but a good contemporary example would be electric vehicle charging. Have a drive and put £10 of electricity into the battery? £10.50. Don't have a drive and charge your car at a public charger? £12.00. This is hard to justify. A self-employed person working from home pays 5% (0%) VAT to plug in their laptop; rent an office and you pay 20%. This doesn't make much sense, even if this only applies to non-VAT registered businesses.

And all of this misses that point that, whilst electricity is expensive compared to both other sources and to other countries, this is mostly a policy decision. The UK relies more heavily than other developed countries on gas to generate electricity, both increasing prices and price volatilty, but also that policy costs to support the decarbonisation of the grid and the economy have generally been loaded onto electricity prices rather than gas. This latter point goes directly against all economic theory: if you want to encourage switching from gas to electricity, than the taxes to support that transition should be placed on the source you want to reduce. Telling people to electrify, whilst charging more for electricity by policy choice simply makes no sense.

Secondly, cutting taxes tends to have a one-way ratchet effect. Whilst it's politically easy to cut taxes, it's much, much harder to raise them. Essentially this risks being an at least £800m per year gap in government revenues for ever. But, as the UK moves towards net zero, gas boilers become replaced by heat pumps, and society more generally electrifies over other energy sources, electricity will form an ever greater share of consumption, at which point removing the tax revenue from it may be judged to have been an error, but will be politically challenging to reverse.

Thirdly, the distributional effects are worth considering. VAT is often talked of as a regressive tax: as lower-income households spend a greater share of their income, a larger share of their total income is subject to VAT at the point of consumption. This is one the greatest arguments for significantly shrinking, and ideally abolishing, the extensive range of items which are zero-rated for VAT (predominantly food but also including children's clothes, books, and many more). Though lower-income households spend a greater share of their consumption on these items, higher-income households spend more in cash terms on these items, meaning a large share of the lost revenue to the Exchequer from zer-rating these goods is left in higher-income households.

Ultimately, VAT is a broad-based tax, and shouldn't be used to try to redistribute between different parts of the economy. Other parts of the tax system are much better at that (standard, more progressive taxes like income tax in particular).

## Maybe it's worth it?

So, all in all, I'm not keen on this as an approach, but there is one caveat that I would give this, particularly this early in a new government. As economists, tax wonks, policy professionals, etc., it's easy for us to be grumpy and point out (as I've done above) why some policy decisions don't make economic, technocratic sense. But this can involve missing the point that ultimately all policy decisions are political decisions, and we forget this at our peril.

One of the (many) reasons that the Starmer administration failed was that even where it had done things which polled well with the public, it was seemingly incapable of teliing the public what it had done. Whilst communications failure is a poor excuse for policy failure, communications _does_ matter, and is an important part of politics and taking the public with you. This policy has polled well, and sometimes (whilst people like me can hate bad policy polling well), it's part of the narrative, and building a little positive atmosphere early on is unlikely to cause Burnham any sleepless nights. After all, the relentless negativity that came in the early weeks and months of the Starmer administration effectively sunk the ship as it left port.

Does that mean I think this policy is worth it for a short-term political high? Somewhat, but not entirely. If this is just a holding position whilst a longer-term, better policy solution to this is worked out (which might include re-setting the VAT treatment), then I think that this is a tolerable though sub-optimal outcome for a better one in the future. But critically, it only works for me in the short-term. If there is no longer-term, better plan, then this one is bad. If it creates a window of optimsim for something better, then the wonks should swallow their pride and admit that politics needs to win sometimes.