---
title: "Bus fares capped at £2"
subtitle: "A curiously national policy for a pro-devolution PM"
author: "Christian Spence"
date: "2026-07-22"
categories: [burnham, buses, devolution]
draft: true
---

It's only taken Andy Burnham until his third day in post to reverse a policy of the previous Labour administration, delivered by ex-Chancellor Rachel Reeves, and return the country to the glorious _status quo ante_ of his favourite chancellor, Jeremy Hunt.

Hang on.

So, the Conservative-delivered national (well, England), bus fare cap of £2 per single journey is back. We know that bus policy is an important idea for Burnham, where he successfully steered Greater Manchester to be the first area to return buses back to public control under that famously power-to-the-people prime minister beloved of all Labour mayors, Theresa May. (We have her to thank for passing the Bus Services Act 2017.)

Hang on.

Well, politics is politics, after all. Bus fare capping is not a bad policy: predictability and affordability can go a long way, and being able to affordably access transport to school, college, university, work, or public services is a good one. It does have a cost, however. Companies will need subsidising, and only on some routes. For now, this is paid for nationally, but as Burnham himself boasts, Greater Manchester under his mayoralty, kept the £2 cap in place even when the national scheme increased it to £3.

