---
title: "Budget 2026 announced"
subtitle: "A half-term date for a half-term government"
author: "Christian Spence"
date: "2026-07-31"
categories: [budget 2026]
---

Today the government [has announced](https://www.gov.uk/government/news/budget-to-move-power-and-money-out-of-westminster-and-into-every-postcode-around-britain) that the first budget of the new Burnham administration will be delivered by John Healey MP, Chancellor of the Exchequer, on **Wednesday 28 October**, and is customarily immediately after Prime Minister's Questions at 12.30pm.

Falling in the autumn half-term, this will likely cause some challenges for politicos, journalists, and the poor civil servants who have to deal with this, but Economic Analytics will be busy as usual analysing the statement, the reams of documents from HM Treasury and the latest forecasts from the Office for Budget Responsibility.

We're now taking bookings from clients for an analysis of the Budget in the days that follow. If you'd like to book Christian Spence to speak to you and/or your clients, please [contact us](/contact.qmd).