---
title: "The new Chancellor's speech to conference"
subtitle: "A lot of history, not a lot of future"
author: "Christian Spence"
date: "2026-09-28"
categories: [labour conference, john healey, budget 2026]
---

In some ways, considering the key points of the speech to the Labour conference in Liverpool of the new Chancellor of the Exchequer, John Healey, is an easy ask. Sadly, that's because there aren't any key points in it.

I don't envy John Healey his job. Picking up the pieces of everything that litters the UK economy from the global financial crisis, austerity, Brexit, Covid, Truss, etc. is no mean feat. I always had sympathy for Starmer and Reeves as they came to power as there wasn't really a policy area that wasn't a burning skip, screaming for attention and almost always requiring new money that wasn't readily available.

The switch from the Conservatives to Labour in 2024 provided, even amongst friends and clients who would not describe themselves as left-wingers, a breathing spot. A little respite. A thought that, whilst what might come next might not be exactly to their taste, drawing a line under the chaos of the post-2016 political system will be a relief. Sadly, Starmer and Reeves blew that brief window of optimism and hope, clouded their vision with an "everything's awful" tint, and sacrificed - unnecessarily - what political capital they had with some self-enforced policy errors.

The change from Starmer to Burnham in July provided the same sort of opportunity. Burnham's speech on arriving in Downing Street provided a clearer sense of the scale of the change and, perhaps more importantly, the tone. That needed to be supported by his chancellor who faces a Herculean task at the budget in October to set out how that will emerge over the rest of this parliament. If this speech was meant to start that conversation, to set out the narrative of what is to come, it failed.

Whether you saw the speech or not, [I encourage you to read it](https://labour.org.uk/updates/stories/john-healeys-speech-to-labour-party-conference-2026/). The layout alone says everything you need to know. The same short, pithy, vacuous sentences and paragraphs set out by a speechwriter who's never had a fully-formed, cogent, coherent thought in their life and who has never persuaded anyone, let alone themselves, of anything. A speech written for a social-media addled world, where holding a train of though for longer than a ten-word sentence or a five-second video short is beyond the bounds of human reason.

Great politicians, great statesmen, great leaders, must all think in prose. You need not only an idea, but the ability to build its case, to set out your intellectual, philosophical, political framework for why you believe it and, critically, why others should believe in it, too. This speech had none of that and, more concerningly, nothing the chancellor has said since coming into the post suggests any deeper thinking, either.

There are still nearly three years of this parliament left. The global situation is not improving, whether we look at energy markets, capital markets or the need for greater defence. Much of the UK public realm is in need of deep repair, and public services require investment. The current baseline plans for this parliament, set out by Rachel Reeves, imply spending cuts to departments in the election year, and the fiscal situation has got worse since then.

The Budget in October is probably the last chance to set out what is going to be different between now and the next election. The chancellor's speech today suggests that it will go every bit as well as the last two. We need better.