on:
  push:
  workflow_dispatch:
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy site
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Checkout repository
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.EA_FTP_SERVER }}
        username: ${{ secrets.EA_FTP_USERNAME }}
        password: ${{ secrets.EA_FTP_PASSWORD }}
        local-dir: _site/
        server-dir: public_html/